### ISSUE TITLE
output.rs uses unnecessary unsafe code

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/core#128]
There are several `AtomicBool`s that are declared `static mut` and accessing `static mut` data requires unsafe code. However, atomics use interior mutability, so it's not necessary to declare these variable `static mut`; `static` will suffice and therefore the `unsafe` code to get/set these atomics can be removed.

Additionally, one of the atomics is named [`NO_COLOR`](https://github.com/habitat-sh/core/blob/master/components/core/src/output.rs#L49) with the comment:
```rust
// I am sorry this isn't named the other way; I can't get an atomic initializer that defaults to
// true. Them's the breaks.
```

This is no longer true; the following is legal since the introduction of `const fn`:
```rust
static COLOR: AtomicBool = AtomicBool::new(true);
```

**Comment by mwrock** [comment]
closed via https://github.com/habitat-sh/habitat/pull/6256
